from turtle import *

speed(1000000)

bgcolor("green")


forward(200)
left(90)
forward(200)
left(90)
forward(200)
left(90)
forward(200)
left(90)




#mze gavakete
begin_fill()
color("yellow")
penup()
goto(250,250)
pendown()


circle(30)
end_fill()

penup()
goto(200,200)
pendown()
left(135)
forward(140)
left(90)
forward(143)

penup()
goto(55,0)
pendown()

right(137)
forward(90)

right(90)
forward(60)
right(90)
forward(90)

penup()
goto(150,150)
pendown()
left(90)
forward(52)
right(90)
forward(52)
right(90)
forward(52)
right(90)
forward(52)


exitonclick()