#work1
name = input("data: " )
surname = input("turkadze: " ) 
print(name + " " + surname)

#work2
nam1 = input (90)
nam2 = input (65)
print(nam1 + " " + nam2) 

#work3
nam1 = input (13)
nam2 = input (12)
nam3 = input (20)
print(nam1 + nam2 + nam3)
print(45/3)

#work4
name = "data"
num = 5
print(name * num)

nam1 = 16
nam2 = 5
print(nam1 * nam2)

#work5
nam1 = 40
nam2 = 10
print(nam1 + nam2)
print(nam1 - nam2)
print(nam1 * nam2)
print(nam1 / nam2)
